spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ProjectPortfolio
    username: ProjectPortfolioUser
    password: root

  mail:
    host: smtp.example.com
    username: example@example.com
#    The password is the email authorization code
    password: yourpassword
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
#          ssl:
#            enable: false
#            required: false
          auth: true
          starttls:
            enable: true
#        debug: true

  data:
    redis:
      host: localhost
      port: 6379

app:
  api-url: "http://localhost:8080"
  allowed-email-domains: amdaris.com, gmail.com